src/app/dashboard/route.ts, src/configs/urls.ts, src/server/middleware.ts, src/server/team/team-actions.ts
this pr adds a new route on `/dashboard` which maps `?tab=xy` values to the correct dashboard urls with the correct selected team for the user. it also disables the middleware "gateway" to not redirect to `/dashboard/xy/sandboxes` route if `/dashboard `has a `tab` search param.
reason for this is that we may want to "deeplink" users to a specific dashboard tab, without knowing their team ids. this is currently used inside our documentation, when the prose links to dashboard tabs. (e.g /dashboard?tab=sandboxes)
=> Redirect dashboard?tab=xy to corresponding team dashboard tab 

next.config.mjs, vercel.json
the new dashboard removed the `/auth `prefix for` /sign-in` `/sign-up` & `/forgot-password`. due to backwards compatibility with having the old dashboard in prod & the new dashboard in testing for certain teams, we should have a redirect in place
=> Add auth url redirects for backwards compatibility

src/features/dashboard/templates/table-config.tsx
this pr adds a minSize attribute to the `name` column in templates table to prevent to small column sizing & truncates the data when it overflows
=> Fix templates name column min size & truncation

README.md
This pr adds the following instructions to the README for self-hosters:
1. supabase callback url setup
2. supabase auth provider setup
3. database setup
=> Update README with missing self-hosting instructions

bun.lock, package.json, src/configs/domains.ts, src/server/auth/validate-email.ts, src/server/middleware.ts
Although mentioned in [CVE-2025-29927](https://github.com/advisories/GHSA-f82v-jwr5-mffw), the version upgrade to resolve the security vulnerability in NextJs in #18 was not enough to fix rewriting issues. This pr explored ways to get around the 406 blockage and in the end settled on:
- using `NextResponse.rewrite` instead of `fetch & new NextResponse`
This approach is far from ideal in terms of performance. It seems like the native NextJs rewrite is doing a lot under the hood before sending the html to the client, potentially adapting additional assets loaded by the rewritten site, as this latency seems to increase with more assets.
=> Fix middleware rewrite handling to comply with CVE-2025-29927

README.md
This pr contains `README` changes that help to resolve confusions seen in #17:
1. note for self-hosters to probably also host their own E2B infrastructure first
2. clarify kv store set-up and integration
=> Add clarification on self-hosting the dashboard application

src/features/dashboard/sandboxes/header.tsx, src/features/dashboard/sandboxes/table-body.tsx, src/features/dashboard/sandboxes/table-config.tsx, src/features/dashboard/sandboxes/table-header.tsx, src/features/dashboard/sandboxes/table-row.tsx, src/features/dashboard/sandboxes/table.tsx, src/server/sandboxes/get-team-sandboxes.ts, src/ui/json-popover.tsx
Because of production issues with the /sandboxes/metrics route and in order to unblock the launch of the new dashboard, this pr temporarily refactors:
1. sandboxes page ui artifacts related to metrics
2. how sandboxes are retrieved from api (`/sandboxes/metrics` -> `/sandboxes`)
=> Refactor /sandboxes/metrics to /sandboxes

src/features/dashboard/templates/by-e2b-badge.tsx, src/features/dashboard/templates/table-config.tsx, src/server/middleware.ts, src/ui/help-tooltip.tsx
We have default templates made by e2b which are indicated in the templates table. Before this change, this was done through a table column with the value "Yes" inside if true. Now we have a dedicated tooltip "By E2B" badge next to the name if a template is a default template.
=> Re-design templates table made by e2b indication

src/server/team/get-team-members.ts
due to internal issues with the previous approach & to safe on resources and latency, this pr updates the team access check for `get-team-members`
=> Improve user teams access check for team members retrieval

public/.well-known/security.txt
Added file under `/.well-known/security.txt` to match security standards for security or abuse reports.
More details why this is well known address by search engines or security researchers can be found here:
[https://www.rfc-editor.org/rfc/rfc9116](https://www.rfc-editor.org/rfc/rfc9116)
=> Add well-known security

src/features/dashboard/sandboxes/table-config.tsx, src/features/dashboard/sandboxes/table.tsx, src/features/dashboard/templates/table-config.tsx
Currently the table date time columns sorted based on their date time string representations. This pr fixes this, along with disabling multiple sortings at once, since this behavior was confusing users.
=> Fix table sorting function to not sort based on date time string

src/app/(rewrites)/[[...slug]]/route.ts
As a result of pausing the work on our Changelog, this pr removes the rewrite for `/changelog` routes/
=> Remove /changelog rewrite

src/app/dashboard/layout.tsx
This pr resolves a partial pre-rendering issue that is only detectable in production when hosting on Vercel. It removes the Promise.all which prevents NextJs to bail out of static rendering correctly.
=> Remove promise.all in layout to prevent ppr issues

.env.example, src/app/(rewrites)/[[...slug]]/route.ts, src/app/layout.tsx, src/app/robots.ts, src/app/sitemap.ts, src/features/dashboard/sandboxes/table-config.tsx, src/lib/clients/action.ts, src/lib/env.ts, src/lib/utils/flags.ts
In order to prevent search engine indexing for our staging / juliett dashboards, but keep rewriting intact for each, this pr adds a NO_INDEX environment variable which takes precautions to tell site crawlers to not index this site.
Additionally this pr:
- adds a NEXT_PUBLIC_VERBOSE environment variable, for better observability in production builds if needed
- try-catches json serialization for sandboxes metadata search
=> Add NO_INDEX & VERBOSE flags

src/app/robots.ts
This pr fixes the `sitemap.xml` reference url in `robots.txt` and handles NO_INDEX cases with a 200 response instead of block site crawlings because we want the crawlers to identify `noindex, nofollow` meta tags to ensure no seo indexing
=> Fix robots sitemap url & improve robots NO_INDEX handling

src/configs/rewrites.ts
To fix data fetching issues on our `/cookbook` route, we move the rewrite to the middleware using nextjs native rewrites instead of fetch html rewrites.
=> Update rewrite cookbook page in middleware

src/configs/keys.ts, src/features/dashboard/sandboxes/stores/table-store.ts, src/features/dashboard/sidebar/menu.tsx, src/features/dashboard/team/name-card.tsx, src/features/dashboard/team/profile-picture-card.tsx, src/lib/hooks/use-server-context.tsx, src/server/team/get-team.ts, src/server/team/types.ts, src/types/actions.d.ts, src/types/dashboard.d.ts, src/types/dashboard.types.ts, src/ui/polling-button.tsx, src/ui/primitives/avatar.tsx
Currently default teams for users get the email of the owner assigned as the name. We had reports that this confused people. To make default team appearances more user friendly, we will transform default "unchanged" team names as follows in the ui:
`ben.fornefeld@gmail.com` -> `Ben.fornefeld's Team`
This is done by appending `transformed_default_name` attribute to the `ClientTeam` type, when a team has a default "unchanged" team name, in the `getUserTeams` server function.
To further clear up confusion, when navigating to `/team`, default transformed team names receive a hint "Seen as - Ben Fornefeld's Team" under the team name settings.
Also this pr:
1. adds object-cover to profile pictures
2. improves avatar uploading rendering
3. removes unused storage/state keys
=> Improve ux for default "email" team names

src/features/dashboard/sandboxes/table-config.tsx
The infra sends `sandboxID` and `clientID` which need to be constructed client side to get the correct sandbox id usable for users. This pr fixes this issue. Also it improves the UX by increasing the min column size, for users to see the full id by default.
=> Fix client side sandbox id construction

src/features/dashboard/usage/cost-card.tsx, src/features/dashboard/usage/ram-card.tsx, src/features/dashboard/usage/sandboxes-card.tsx, src/features/dashboard/usage/sandboxes-chart.tsx, src/features/dashboard/usage/vcpu-card.tsx
This pr improves the sandboxes chart code to be more readable + adds an indication for the current month (billing period) to be easily comparable with the other usage charts. Also this pr improves the general prose of the usage page to be more in sync with what the components show.
=> Improve usage page prose

src/app/(auth)/auth/cli/page.tsx, src/app/api/team/state/route.ts, src/features/dashboard/account/user-access-token.tsx, src/features/dashboard/sidebar/menu.tsx, src/lib/utils/server.ts, src/server/auth/get-default-team.ts, src/server/user/user-actions.ts, src/types/api.d.ts
In order to be prepared for our upcoming migration to hashed api keys, this pr introduces the following changes:
1. create new access tokens for cli auth & access token retrieval under `dashboard/account`
2. remove api key return in `/auth/cli`, since it is not required in the cli
Additionally but not entangled, it adds route for manual team selection cookie updates, to fix changing teams on a non team dependent route (e.g `/dashboard/account`)
=> Prepare cli auth & access token retrieval for api key hashing

src/features/dashboard/billing/tier-card.tsx
Currently tier handling / indication is not ideal and will be refactored soon. As a quick fix to handle correct plan indication for custom tiers, this pr adds a check if the tier id contains "pro" or "enterprise"
=> Fix pro tier indication for custom tiers

src/middleware.ts
This pr fixes the forwarding of request headers, including the `x-e2b-should-index` header, by utilizing the correct `NextResponse.rewrite` property `request` for overriding the rewritten `request` inits
=> Fix: correct middleware rewrites request header forwarding

src/app/api/auth/confirm/route.ts
This pr get's rid of "confirmationUrl" on the OTP flow and rather build the url itself when needed.
=> Fix: Fix redirecting to the correct Supabase PKCE flow for external origin requests

src/app/api/auth/confirm/route.ts
This pr removes "confirmation_url" from /api/auth/confirm schema validation
=> Remove: confirmation_url schema validation

bun.lock, package.json
- Changed Next.js version from `^15.4.2-canary.16` to `15.3.0-canary.23` in both `bun.lock` and `package.json`.
- Updated various dependencies related to `sharp` and `@next` packages to their respective versions, ensuring compatibility with the downgraded Next.js version.
The previous version produced issued with the catch-all rewrites in [here](https://github.com/e2b-dev/dashboard/blob/14dd8c6849806ab325abc65c36b44b4ff59af492/src/app/(rewrites)/%5B%5B...slug%5D%5D/route.ts#L4)
=> Patch: Downgrade Next.js version 

next.config.mjs, src/configs/rewrites.ts, vercel.json
This pr adds a new redirection section inside the next apps config, for campaign redirects to campaign resources. Also this pr exposes `/enterprise` and /`careers` inside the catch-all rewrite handler, to rewrite from the landing page.
=> Feat: Add Campaigns redirects + Expose new proxy route

next-logger.config.ts, src/app/dashboard/[teamIdOrSlug]/sandboxes/page.tsx, src/server/sandboxes/get-team-sandboxes.ts
The current implementation uses infra api route `/v2/sandboxes` to list the sandboxes, which uses server side pagination. it did not cause unexpected behavior yet, since the default limit for entries on a paginated slice is 1000 sandboxes. Since we officially do not use the pagination in the dashboard implementation, this basically is a hard cap at 1000 concurrent sandboxes.
This pr: 
- reverts this change to use the legacy sandbox list endpoint for now
- adds improvements for the initial sandbox metrics fetching
=> Fix: Sandbox list capped at 1000 entries

src/features/dashboard/sandbox/header/remaining-time.tsx
This pr refactors / fixes the "Timeout In" header on the sandbox details page, to make sure sandbox timeouts that exceed 1 hour are counted and displayed correctly.
=> Fix: Add hours display and improve remaining time calculation logic

src/__test__/integration/auth.test.ts, src/app/(auth)/sign-in/page.tsx, src/app/(auth)/sign-up/page.tsx, src/lib/schemas/url.ts
This pr adds two new auth tests, which both check for the same validation error on sign-in. Also this pr improves the relative path validator and how `returnTo` is handled inside sign-in and sign-up.
=> Improve: Enhance auth tests + relative url path validator

src/__test__/unit/chart-utils.test.ts, src/features/dashboard/sandboxes/monitoring/charts/concurrent-chart.client.tsx, src/features/dashboard/sandboxes/monitoring/charts/utils.tsx
Fixed an issue where charts would cap the y-axis at the limit line even when actual data exceeded it, potentially cutting off data points.
- Y-axis now scales to `maxValue * 1.1` when data exceeds the defined limit
- When data is below limit, y-axis shows `limit * 1.1` to keep the limit line visible
- Maintains clean axis values through snapping (10s, 50s, 100s, etc)
Data points above limits could be cut off or squished against the top of charts
Charts properly scale to show all data while keeping limit lines as visual reference points
Fixes chart readability when sandboxes spike above configured limits.
=> Fix: improve y-axis scaling when data exceeds chart limits

bun.lock, package.json, src/app/layout.tsx
This PR add's `@vercel/speed-insights` SDK, which will enable us to monitor our dashboards performance more closely.
=> Feat: vercel speed analytics

src/lib/utils/action.ts, src/server/billing/billing-actions.ts
This pr adds supabase team authorization headers to the billing /checkout api call, to prepare for the route requiring it as a parameter.
=> Patch: Add supabase authorization headers to stripe checkout endpoint

.gitignore, src/server/auth/auth-actions.ts, src/server/user/user-actions.ts, tsconfig.json
This pr add's validation, to ensure that the password a user is trying to sign-up with is not set to his e-mail address. The same validation applies when the user is trying to change his password.
=> Improve: prevent password sign up with e mail as password
